//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace labtaskweek5.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class uo
    {
        public int uoid { get; set; }
        public int uid { get; set; }
        public int oid { get; set; }
    
        public virtual order order { get; set; }
        public virtual user user { get; set; }
    }
}
